application: cornellclassmates
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /.*
  script: main.app
#  secure: always

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "2.5.2"
